# Aula 2 - Phython

## Dados numericos

In [2]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [3]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [4]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [5]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [6]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


# Dados de texto

In [7]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


# Dados tipo bool - lógica

In [8]:
a == 1

True

In [9]:
h = (a==1)
print(h)
type(h)

True


bool

In [10]:
h = (a==2)
print(h)
type(h)

False


bool

In [11]:
i = True
type(i)

bool

In [12]:
ii = 'True'
type(ii)

str

# Operação de comparação

In [13]:
# Operação ==
a==b

True

In [14]:
# Operação ><
a>b

False

In [15]:
# Operação !=
a!=b

False

In [16]:
# Operação >= ou <=
a>=b

True

# Operações matemáticas

In [17]:
# Soma 
a+b

2.0

In [18]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [19]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [20]:
# Divisão
a/b

1.0

In [21]:
# Potencia
5**2

25

In [22]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [23]:
math.exp(0)

1.0

In [24]:
math.exp(a)

2.718281828459045

In [25]:
math.exp(-10)

4.5399929762484854e-05

In [26]:
import math as mt
mt.log(c)

0.0

In [27]:
mt.log10(100)

2.0

# Listas

In [28]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [29]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [30]:
myFirstList==a

False

In [31]:
myFirstList[0]==a

True

In [32]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [33]:
type(mySecList)

list

In [34]:
type(mySecList[2])

str

In [35]:
type(mySecList[1])

int

# Caminhos = path

In [36]:
path = r"C:\Users\alice\OneDrive\Área de Trabalho\UFSC 24.1\Poluicao\ENS51732401"
print(path)

C:\Users\alice\OneDrive\Área de Trabalho\UFSC 24.1\Poluicao\ENS51732401


In [44]:
path = "C:/Users/alice/OneDrive/Área de Trabalho/UFSC 24.1/Poluicao/ENS51732401"
print(path)

C:/Users/alice/OneDrive/Área de Trabalho/UFSC 24.1/Poluicao/ENS51732401


In [45]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore.txt',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'venv']

In [46]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [47]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/alice/OneDrive/Área de Trabalho/UFSC 24.1/Poluicao/ENS51732401/.git'

In [48]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [49]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\alice\\OneDrive\\Área de Trabalho\\UFSC 24.1\\Poluicao\\ENS51732401\\venv\\Scripts'

In [50]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\alice\\OneDrive\\Área de Trabalho\\UFSC 24.1\\Poluicao\\')

In [51]:
os.getcwd()

'C:\\Users\\alice\\OneDrive\\Área de Trabalho\\UFSC 24.1\\Poluicao'

In [52]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\alice\OneDrive\Área de Trabalho\UFSC 24.1\Poluicao/test


In [53]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\alice\OneDrive\Área de Trabalho\UFSC 24.1\Poluicao/test2


# Numpy arrays e Pandas DataFrames

In [54]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [55]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [56]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.347405   0.7103404  0.14942143 0.19783979 0.58592833 0.1089658
  0.03349069 0.2267612  0.08909086 0.52727925]
 [0.86189846 0.79886804 0.07278793 0.82149084 0.45835486 0.99728461
  0.55132104 0.19613227 0.94952005 0.13012928]
 [0.69033214 0.82429002 0.9909738  0.14330905 0.92483009 0.89935039
  0.73642549 0.91987612 0.80445778 0.93984332]
 [0.56476438 0.67139776 0.21270965 0.75351439 0.53564285 0.04746312
  0.01316003 0.70465819 0.21848433 0.26813564]
 [0.1103305  0.5701101  0.32868747 0.77000735 0.75240219 0.70789931
  0.97470751 0.34212634 0.55151747 0.18393275]
 [0.42791186 0.71792692 0.04974777 0.88246822 0.2168899  0.30388347
  0.73961907 0.44043506 0.01604247 0.76012194]
 [0.84512755 0.37916986 0.82376939 0.83295031 0.76230226 0.66655906
  0.49557315 0.80329427 0.68350658 0.32152318]
 [0.83850726 0.69662894 0.76121801 0.97709444 0.9868214  0.42260143
  0.84026122 0.51432807 0.51225052 0.7479516 ]
 [0.87106377 0.29006133 0.42663474 0.36149167 0.7426938  0.04342235
  0.33423122 

In [57]:
# Acessando valores da matriz
n[0,:]

array([0.347405  , 0.7103404 , 0.14942143, 0.19783979, 0.58592833,
       0.1089658 , 0.03349069, 0.2267612 , 0.08909086, 0.52727925])

In [58]:
n[:,0]

array([0.347405  , 0.86189846, 0.69033214, 0.56476438, 0.1103305 ,
       0.42791186, 0.84512755, 0.83850726, 0.87106377, 0.04037465])

In [59]:
n[:,1:5]

array([[0.7103404 , 0.14942143, 0.19783979, 0.58592833],
       [0.79886804, 0.07278793, 0.82149084, 0.45835486],
       [0.82429002, 0.9909738 , 0.14330905, 0.92483009],
       [0.67139776, 0.21270965, 0.75351439, 0.53564285],
       [0.5701101 , 0.32868747, 0.77000735, 0.75240219],
       [0.71792692, 0.04974777, 0.88246822, 0.2168899 ],
       [0.37916986, 0.82376939, 0.83295031, 0.76230226],
       [0.69662894, 0.76121801, 0.97709444, 0.9868214 ],
       [0.29006133, 0.42663474, 0.36149167, 0.7426938 ],
       [0.04298512, 0.81622491, 0.89799292, 0.99731187]])

In [60]:
n[0,1:5]

array([0.7103404 , 0.14942143, 0.19783979, 0.58592833])

In [61]:
n[0,-1]

0.5272792484649643

In [62]:
n[0,4:-1]

array([0.58592833, 0.1089658 , 0.03349069, 0.2267612 , 0.08909086])

In [63]:
n[0,4:]

array([0.58592833, 0.1089658 , 0.03349069, 0.2267612 , 0.08909086,
       0.52727925])

In [64]:
an = np.log(n*5)
print(an)

[[ 0.55217389  1.26742693 -0.29154664 -0.01085979  1.07488011 -0.6072833
  -1.78704979  0.1255801  -0.80866058  0.96941292]
 [ 1.46082011  1.38487842 -1.01076724  1.41280342  0.82932633  1.60671883
   1.01399992 -0.01952807  1.55763928 -0.42978894]
 [ 1.23885547  1.41620507  1.60037073 -0.33331388  1.53129267  1.50335535
   1.30349069  1.52592165  1.39185111  1.54739581]
 [ 1.03809126  1.21104438  0.06161073  1.32643074  0.98515025 -1.43836442
  -2.7211333   1.25939548  0.08839692  0.29317559]
 [-0.59483697  1.04751214  0.49678999  1.34808269  1.32495364  1.26398451
   1.58382007  0.53686273  1.01435616 -0.08374717]
 [ 0.76059986  1.27805042 -1.39135166  1.48440541  0.08107248  0.41832692
   1.30781791  0.78944563 -2.5230778   1.3351615 ]
 [ 1.4411702   0.63966693  1.41557325  1.42665662  1.33802578  1.20381138
   0.9073976   1.39040375  1.22891892  0.47475227]
 [ 1.43330587  1.24793553  1.33660243  1.58626595  1.5961717   0.74811211
   1.43539545  0.94454397  0.94049644  1.3190209 ]
 